// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Models;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(VoteContext))]
    [Migration("20230616113501_clearmig")]
    partial class clearmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibModels.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVoted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 25464464654L,
                            IsVoted = false,
                            Name = "Batuhan",
                            SurName = "Çetin"
                        },
                        new
                        {
                            Id = 23454545454L,
                            IsVoted = false,
                            Name = "Cenk",
                            SurName = "Çetin"
                        });
                });

            modelBuilder.Entity("LibModels.Candidate", b =>
                {
                    b.HasBaseType("LibModels.User");

                    b.Property<long>("VoteCount")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("Candidate");

                    b.HasData(
                        new
                        {
                            Id = 12341234123L,
                            IsVoted = false,
                            Name = "Aday1",
                            SurName = "Çetin",
                            VoteCount = 0L
                        },
                        new
                        {
                            Id = 23412312341L,
                            IsVoted = false,
                            Name = "Aday2",
                            SurName = "Çetin",
                            VoteCount = 0L
                        },
                        new
                        {
                            Id = 23123412341L,
                            IsVoted = false,
                            Name = "Aday3",
                            SurName = "Çetin",
                            VoteCount = 0L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
